export const CHESS_RULE_VIOLATION_TYPES = {
  INVALID_PLACEMENT: 'INVALID_PLACEMENT',
  INVALID_PROMOTION: 'INVALID_PROMOTION',
  INVALID_PLAYER_TURN: 'INVALID_PLAYER_TURN',
  INVALID_OWN_KING_IN_CHECK: 'INVALID_OWN_KING_IN_CHECK',
} as const;

export type ChessRuleViolationType =
  (typeof CHESS_RULE_VIOLATION_TYPES)[keyof typeof CHESS_RULE_VIOLATION_TYPES];
