export const CHESS_RULE_VIOLATION_TYPES = {
  INVALID_PLACEMENT: 'INVALID_PLACEMENT',
  INVALID_PLACEMENT_NO_CURRENT_POSITION: 'INVALID_PLACEMENT_NO_CURRENT_POSITION',
  INVALID_PLACEMENT_CANNOT_REACH_POSITION: 'INVALID_PLACEMENT_CANNOT_REACH_POSITION',
  INVALID_PROMOTION: 'INVALID_PROMOTION',
  INVALID_PROMOTION_MISSING_PROMOTION: 'INVALID_PROMOTION_MISSING_PROMOTION',
  INVALID_PROMOTION_REQUESTED_PIECE_NOT_ALLOWED: 'INVALID_PROMOTION_REQUESTED_PIECE_NOT_ALLOWED',
  INVALID_PLAYER_TURN: 'INVALID_PLAYER_TURN',
  INVALID_OWN_KING_IN_CHECK: 'INVALID_OWN_KING_IN_CHECK',
  NOT_MOVED: 'NOT_MOVED',
} as const;

export type ChessRuleViolationType =
  (typeof CHESS_RULE_VIOLATION_TYPES)[keyof typeof CHESS_RULE_VIOLATION_TYPES];
