name: Docker Build

on:
  workflow_call:

permissions:
  contents: read

jobs:
  docker-build:
    name: Docker Build Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build .